name: CI

on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  KHULNASOFT_EXTENSION_CLI_SHA: 5a25751521d3f6e9da51eb5d0af34dc25d9b7ce8

jobs:
  package:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'khulnasoft'
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          clean: false
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Cache khulnasoft-extension CLI
        id: cache-khulnasoft-extension
        uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4
        with:
          path: |
            khulnasoft-extension
          key: khulnasoft-extension-${{ env.KHULNASOFT_EXTENSION_CLI_SHA }}

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Cache extension build dependencies
        uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4
        with:
          key: cache-build-dependencies
          path: |
            ./scratch

      - name: Enforce sorted `plugins.toml` and `.gitmodules`
        run: |
          if ! git diff --exit-code -- plugins.toml .gitmodules; then
            echo -e "\nERROR: plugins.toml and .gitmodules are not sorted."
            echo -e "Fix by running:\n  pnpm sort-plugins\n"
            exit 1
          fi
